/**
 * MT5 Auto-Trading Type Definitions
 *
 * These types define the data structures for the MT5 auto-trading bridge.
 * The Python bot on VPS and the Vercel API communicate via Supabase (shared state).
 *
 * Tables in Supabase:
 * - mt5_signals    — AI-generated trade signals awaiting auto-execution
 * - mt5_positions  — Open/closed positions synced from MT5
 * - mt5_bot_status — Bot connection status (single row, updated by bot)
 * - mt5_config     — Auto-trading configuration (single row, updated by user)
 * - mt5_accounts   — Multi-client broker accounts with risk management
 * - mt5_daily_logs — Daily P&L tracking history
 * - mt5_trade_log  — Detailed trade log
 */

// ======================== MT5 SIGNAL ========================

export type MT5SignalStatus = 'pending' | 'executed' | 'skipped' | 'expired' | 'failed';
export type MT5SignalDirection = 'BUY' | 'SELL';

/** MT5 Signal — generated by AI analysis, waiting for auto-execution */
export interface MT5Signal {
  id: string;
  symbol: string;
  direction: MT5SignalDirection;
  entry_price: number;
  stop_loss: number;
  take_profit: number;
  confidence: number;
  strategy: string;
  lot_size: number;
  status: MT5SignalStatus;
  error_message?: string;
  created_at: string;
  executed_at?: string;
}

/** Payload for creating a new signal */
export interface MT5SignalCreatePayload {
  symbol: string;
  direction: MT5SignalDirection;
  entry_price: number;
  stop_loss: number;
  take_profit: number;
  confidence: number;
  strategy: string;
  lot_size: number;
}

// ======================== MT5 POSITION ========================

export type MT5PositionStatus = 'open' | 'closed' | 'error';

/** MT5 Position — open/closed positions in MT5 */
export interface MT5Position {
  id: string;
  ticket: number;
  symbol: string;
  direction: MT5SignalDirection;
  lot_size: number;
  entry_price: number;
  stop_loss: number;
  take_profit: number;
  current_price: number;
  profit: number;
  profit_pips: number;
  open_time: string;
  close_time?: string;
  status: MT5PositionStatus;
  signal_id?: string;
}

// ======================== MT5 BOT STATUS ========================

/** MT5 Bot Status — connection status (single row, updated by bot) */
export interface MT5BotStatus {
  id: string;
  connected: boolean;
  mt5_connected: boolean;
  account_balance: number;
  account_equity: number;
  account_leverage: number;
  account_currency: string;
  open_positions_count: number;
  last_heartbeat: string;
  server_time: string;
  bot_version: string;
  mt5_terminal_path: string;
  // Broker info (display)
  mt5_login: number;
  mt5_server: string;
  mt5_account_type: 'demo' | 'live';
}

// ======================== MT5 CONFIG ========================

/** Lot sizing mode */
export type MT5LotType = 'fixed' | 'percentage';

/** MT5 account type */
export type MT5AccountType = 'demo' | 'live';

/** MT5 Config — auto-trading configuration (single row, updated by user) */
export interface MT5Config {
  id: string;
  auto_trading_enabled: boolean;
  max_lot_size: number;
  risk_per_trade_pct: number;
  allowed_symbols: string[];  // stored as JSON string in Supabase
  max_open_positions: number;
  min_confidence: number;
  strategy_filter: string[];  // stored as JSON string in Supabase
  stop_loss_default_pips: number;
  take_profit_default_pips: number;
  trading_hours_start: string;  // "09:00"
  trading_hours_end: string;    // "17:00"
  updated_at: string;

  // Broker connection (client enters credentials on the website)
  mt5_login: number;           // MT5 account number
  mt5_password: string;        // MT5 password (stored in Supabase, read by bot)
  mt5_server: string;          // Broker server (e.g., "MetaQuotes-Demo")
  mt5_account_type: MT5AccountType;  // 'demo' or 'live'

  // Risk management
  profit_target: number;       // Daily profit target in account currency (0 = disabled)
  loss_limit: number;          // Daily loss limit in account currency (0 = disabled)
  lot_type: MT5LotType;        // 'fixed' = use fixed_lot, 'percentage' = calculate from balance
  lot_percentage: number;      // Risk % per trade when lot_type='percentage'
  fixed_lot: number;           // Fixed lot size when lot_type='fixed'

  // Daily P&L tracking (updated by bot)
  daily_pnl: number;           // Accumulated daily P&L
  daily_pnl_date: string | null;  // Date of current daily P&L tracking
}

/** Payload for updating config (partial, all fields optional) */
export interface MT5ConfigUpdatePayload {
  auto_trading_enabled?: boolean;
  max_lot_size?: number;
  risk_per_trade_pct?: number;
  allowed_symbols?: string[];
  max_open_positions?: number;
  min_confidence?: number;
  strategy_filter?: string[];
  stop_loss_default_pips?: number;
  take_profit_default_pips?: number;
  trading_hours_start?: string;
  trading_hours_end?: string;

  // Broker connection
  mt5_login?: number;
  mt5_password?: string;
  mt5_server?: string;
  mt5_account_type?: MT5AccountType;

  // Risk management
  profit_target?: number;
  loss_limit?: number;
  lot_type?: MT5LotType;
  lot_percentage?: number;
  fixed_lot?: number;

  // Daily P&L (updated by bot)
  daily_pnl?: number;
  daily_pnl_date?: string | null;
}

// ======================== SIGNAL STATS ========================

/** Statistics for signals */
export interface MT5SignalStats {
  total_signals: number;
  pending_signals: number;
  executed_signals: number;
  skipped_signals: number;
  expired_signals: number;
  failed_signals: number;
  win_count: number;
  loss_count: number;
  win_rate: number;
  total_profit_pips: number;
  average_confidence: number;
}

// ======================== MT5 ACCOUNT (NEW) ========================

/** MT5 Account — multi-client broker accounts with risk management */
export interface MT5Account {
  id: string;
  client_id: string;
  client_name: string;
  broker_login: number;
  broker_password: string;
  broker_server: string;
  account_type: MT5AccountType;
  account_balance: number;
  account_equity: number;
  account_leverage: number;
  account_currency: string;
  is_active: boolean;
  auto_trading_enabled: boolean;
  profit_target: number;
  loss_limit: number;
  lot_type: MT5LotType;
  lot_percentage: number;
  fixed_lot: number;
  max_lot_size: number;
  risk_per_trade_pct: number;
  max_open_positions: number;
  min_confidence: number;
  stop_loss_default_pips: number;
  take_profit_default_pips: number;
  daily_pnl: number;
  daily_pnl_date: string | null;
  last_connected_at: string | null;
  created_at: string;
  updated_at: string;
}

/** Payload for creating a new account (partial, required fields + optional overrides) */
export interface MT5AccountCreatePayload {
  client_id: string;
  client_name: string;
  broker_login: number;
  broker_password: string;
  broker_server: string;
  account_type?: MT5AccountType;
  account_balance?: number;
  account_equity?: number;
  account_leverage?: number;
  account_currency?: string;
  is_active?: boolean;
  auto_trading_enabled?: boolean;
  profit_target?: number;
  loss_limit?: number;
  lot_type?: MT5LotType;
  lot_percentage?: number;
  fixed_lot?: number;
  max_lot_size?: number;
  risk_per_trade_pct?: number;
  max_open_positions?: number;
  min_confidence?: number;
  stop_loss_default_pips?: number;
  take_profit_default_pips?: number;
}

/** Payload for updating an account (all fields optional) */
export interface MT5AccountUpdatePayload {
  client_id?: string;
  client_name?: string;
  broker_login?: number;
  broker_password?: string;
  broker_server?: string;
  account_type?: MT5AccountType;
  account_balance?: number;
  account_equity?: number;
  account_leverage?: number;
  account_currency?: string;
  is_active?: boolean;
  auto_trading_enabled?: boolean;
  profit_target?: number;
  loss_limit?: number;
  lot_type?: MT5LotType;
  lot_percentage?: number;
  fixed_lot?: number;
  max_lot_size?: number;
  risk_per_trade_pct?: number;
  max_open_positions?: number;
  min_confidence?: number;
  stop_loss_default_pips?: number;
  take_profit_default_pips?: number;
  daily_pnl?: number;
  daily_pnl_date?: string | null;
  last_connected_at?: string | null;
}

// ======================== MT5 DAILY LOG (NEW) ========================

/** MT5 Daily Log — daily P&L tracking history */
export interface MT5DailyLog {
  id: string;
  account_id: string;
  log_date: string;
  start_balance: number;
  end_balance: number;
  start_equity: number;
  end_equity: number;
  total_pnl: number;
  total_trades: number;
  winning_trades: number;
  losing_trades: number;
  total_profit: number;
  total_loss: number;
  largest_win: number;
  largest_loss: number;
  created_at: string;
  updated_at: string;
}

/** Payload for creating a daily log entry */
export interface MT5DailyLogCreatePayload {
  account_id: string;
  log_date: string;
  start_balance?: number;
  end_balance?: number;
  start_equity?: number;
  end_equity?: number;
  total_pnl?: number;
  total_trades?: number;
  winning_trades?: number;
  losing_trades?: number;
  total_profit?: number;
  total_loss?: number;
  largest_win?: number;
  largest_loss?: number;
}

// ======================== MT5 TRADE LOG (NEW) ========================

/** Trade direction for trade log */
export type MT5TradeDirection = 'BUY' | 'SELL';

/** Trade result for trade log */
export type MT5TradeResult = 'win' | 'loss' | 'breakeven' | 'open';

/** MT5 Trade Log — detailed trade log */
export interface MT5TradeLog {
  id: string;
  account_id: string;
  signal_id: string | null;
  ticket: number;
  symbol: string;
  direction: MT5TradeDirection;
  lot_size: number;
  entry_price: number;
  exit_price: number | null;
  stop_loss: number;
  take_profit: number;
  profit: number;
  profit_pips: number;
  commission: number;
  swap: number;
  open_time: string;
  close_time: string | null;
  duration_minutes: number | null;
  result: MT5TradeResult;
  strategy: string;
  confidence: number;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

/** Payload for creating a trade log entry */
export interface MT5TradeLogCreatePayload {
  account_id: string;
  signal_id?: string | null;
  ticket: number;
  symbol: string;
  direction: MT5TradeDirection;
  lot_size?: number;
  entry_price?: number;
  exit_price?: number | null;
  stop_loss?: number;
  take_profit?: number;
  profit?: number;
  profit_pips?: number;
  commission?: number;
  swap?: number;
  open_time?: string;
  close_time?: string | null;
  duration_minutes?: number | null;
  result?: MT5TradeResult;
  strategy?: string;
  confidence?: number;
  notes?: string | null;
}
