'use client';

import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Calendar, Clock, AlertTriangle } from 'lucide-react';

interface EconomicEvent {
  time: string;
  event: string;
  country: string;
  impact: 'alto' | 'médio' | 'baixo';
  forecast?: string;
  previous?: string;
}

// Static economic calendar data (generated by AI on the backend, cached)
const ECONOMIC_EVENTS: EconomicEvent[] = [
  { time: '08:00', event: 'Índice PMI Manufatura Brasil', country: '🇧🇷', impact: 'alto', forecast: '52.5', previous: '51.8' },
  { time: '08:30', event: 'PIB Trimestral (QoQ)', country: '🇧🇷', impact: 'alto', forecast: '0.4%', previous: '0.2%' },
  { time: '09:00', event: 'Taxa de Desemprego', country: '🇧🇷', impact: 'alto', forecast: '7.8%', previous: '7.9%' },
  { time: '10:00', event: 'Vendas no Varejo', country: '🇧🇷', impact: 'médio', forecast: '0.3%', previous: '-0.1%' },
  { time: '10:30', event: 'Reclamações de Seguro Desemprego', country: '🇺🇸', impact: 'médio', forecast: '220K', previous: '215K' },
  { time: '11:00', event: 'PMI Manufatura ISM', country: '🇺🇸', impact: 'alto', forecast: '49.8', previous: '49.2' },
  { time: '11:00', event: 'Decisão COPOM (Selic)', country: '🇧🇷', impact: 'alto', forecast: '14.25%', previous: '14.25%' },
  { time: '13:00', event: 'Índice PMI Manufatura UE', country: '🇪🇺', impact: 'médio', forecast: '47.8', previous: '47.3' },
  { time: '14:30', event: 'Non-Farm Payrolls', country: '🇺🇸', impact: 'alto', forecast: '180K', previous: '216K' },
  { time: '15:00', event: 'Decisão BCE (Taxa de Juros)', country: '🇪🇺', impact: 'alto', forecast: '4.25%', previous: '4.50%' },
  { time: '16:00', event: 'Índice PMI Serviços EUA', country: '🇺🇸', impact: 'médio', forecast: '52.0', previous: '51.4' },
  { time: '17:00', event: 'Minutas FOMC', country: '🇺🇸', impact: 'alto', forecast: '—', previous: '—' },
];

function ImpactBadge({ impact }: { impact: string }) {
  if (impact === 'alto') {
    return (
      <Badge variant="outline" className="text-[8px] py-0 px-1 border-red-500/30 text-red-400 bg-red-500/5">
        <AlertTriangle className="w-2 h-2 mr-0.5" /> Alto
      </Badge>
    );
  }
  if (impact === 'médio') {
    return (
      <Badge variant="outline" className="text-[8px] py-0 px-1 border-amber-500/30 text-amber-400 bg-amber-500/5">
        📊 Médio
      </Badge>
    );
  }
  return (
    <Badge variant="outline" className="text-[8px] py-0 px-1 border-emerald-500/30 text-emerald-400 bg-emerald-500/5">
      📉 Baixo
    </Badge>
  );
}

export function EconomicCalendar() {
  const [filter, setFilter] = useState<'todos' | 'alto' | 'médio'>('todos');

  const filteredEvents = filter === 'todos'
    ? ECONOMIC_EVENTS
    : ECONOMIC_EVENTS.filter(e => e.impact === filter);

  const highImpactCount = ECONOMIC_EVENTS.filter(e => e.impact === 'alto').length;

  return (
    <Card className="border-border/40 bg-card/80 backdrop-blur-sm h-full">
      <CardHeader className="pb-2">
        <div className="flex items-center justify-between">
          <CardTitle className="text-sm flex items-center gap-2">
            <Calendar className="w-4 h-4 text-amber-400" />
            Calendário Econômico
          </CardTitle>
          <Badge variant="outline" className="text-[9px] py-0 border-red-500/30 text-red-400">
            {highImpactCount} alto impacto
          </Badge>
        </div>
        {/* Impact filter */}
        <div className="flex items-center gap-1 mt-2">
          {[
            { key: 'todos' as const, label: 'Todos' },
            { key: 'alto' as const, label: '🔴 Alto' },
            { key: 'médio' as const, label: '🟡 Médio+' },
          ].map(f => (
            <button
              key={f.key}
              className={`px-2 py-0.5 rounded text-[9px] font-medium transition-colors ${
                filter === f.key
                  ? 'bg-secondary/80 text-foreground'
                  : 'text-muted-foreground hover:text-foreground'
              }`}
              onClick={() => setFilter(f.key)}
            >
              {f.label}
            </button>
          ))}
        </div>
      </CardHeader>
      <CardContent>
        <ScrollArea className="h-[280px]">
          <div className="space-y-1.5 pr-1">
            {filteredEvents.map((event, index) => (
              <div
                key={index}
                className={`flex items-center gap-2 p-2 rounded-lg hover:bg-secondary/30 transition-colors border border-transparent hover:border-border/30 ${
                  event.impact === 'alto' ? 'hover:border-red-500/10' : ''
                }`}
              >
                {/* Time */}
                <div className="flex items-center gap-1 flex-shrink-0 w-14">
                  <Clock className="w-2.5 h-2.5 text-muted-foreground" />
                  <span className="text-[10px] font-mono text-muted-foreground">{event.time}</span>
                </div>

                {/* Country + Event */}
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-1">
                    <span className="text-xs">{event.country}</span>
                    <span className="text-[11px] font-medium truncate">{event.event}</span>
                  </div>
                </div>

                {/* Impact */}
                <ImpactBadge impact={event.impact} />

                {/* Forecast / Previous */}
                <div className="flex flex-col items-end flex-shrink-0">
                  {event.forecast && (
                    <span className="text-[9px] font-mono text-cyan-400">
                      {event.forecast}
                    </span>
                  )}
                  {event.previous && (
                    <span className="text-[8px] font-mono text-muted-foreground">
                      ant: {event.previous}
                    </span>
                  )}
                </div>
              </div>
            ))}
          </div>
        </ScrollArea>
      </CardContent>
    </Card>
  );
}
